# Generated by Django 2.0.1 on 2018-02-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='제목', max_length=50),
            preserve_default=False,
        ),
    ]
