# Generated by Django 2.0.1 on 2018-02-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180209_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='due',
            field=models.DateTimeField(verbose_name='마감 기한 #YYYY-MM-DD 형식으로 입력하세요.'),
        ),
    ]
